theme = "diary"
baseURL = "https://blog.likeli.top/"
languageCode = "zh-cn"
title = "Li.Goper"
summaryLength = 70
hasCJKLanguage = true

[params]
  AuthorName = "李科笠"
  GitHubUser = "li-keli"
  Subtitle = "Anything in life worth doing is worth overdoing!"

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "存档"
weight = 1

[[menu.main]]
url = "/tags"
name = "标签"
weight = 2

[[menu.main]]
url = "/categories"
name = "分类"
weight = 3

[[menu.main]]
url = "/bio"
name = "关于我"
weight = 4